Fix 'yamlToJson.mjs'
opening-hours/opening_hours.js pull request #468
Opened 2024-12-30 12:17 UTC by KristjanESPERANTO

- Add missing process import
- Sort imports - Replace 'prettier' by internal function
- Add console output

Side note: I had to add the file `test/test.en.log` to be able to commit. It's unrelated to my changes.

2025-01-01 14:17 UTC, KristjanESPERANTO commented
@ypid: Before I go any further, can you please check if I'm going in the right direction here? My next step would be to review and (if ok) adopt more PRs.

2025-01-02 22:45 UTC, KristjanESPERANTO commented
I think it's more than enough for a release now. Let me know if you don't like anything.

2025-01-22 18:30 UTC, ypid commented
@KristjanESPERANTO Thanks very much for all your work! I am currently working on a private project in my spare time which should be completed by the end of January, then I will pick up this. Sorry for the delay.

2025-01-22 21:01 UTC, KristjanESPERANTO commented
No problem, there's no hurry :slightly_smiling_face:

2025-04-06 16:59 UTC, KristjanESPERANTO commented
If a rebase helps you to review it or anything else, let me know.

2025-04-06 17:04 UTC, ypid requested changes
Only minor things noted. Nice work overall. Thank you very much for all you have done!

2025-04-06 17:04 UTC, ypid commented on scripts/yamlToJson.mjs
>  // Call yamlToJson.mjs [input] [output]
That script was introduced in cda07f85074f934c7358a72d0d1cb0e0ef06f785. You can just drop it. There are better tools like https://mikefarah.gitbook.io/yq that do this. No need to maintain our own.

2025-04-06 17:04 UTC, ypid commented on LICENSES/AGPL-3.0-only.txt
> +Copyright (C) 2007 Free Software Foundation, Inc. <https://www.fsf.org/>
I would also very much like to update the files to https. But those license files are managed/downloaded by https://reuse.software/ and it is more important for me for those files to be bit-by-bit reproducible by the reuse command.

Also, other tools might try to identify the license from those files.

Such changes should be made upstream to the license files. But I am not sure if they accept such changes.

2025-04-06 17:04 UTC, ypid commented on .github/workflows/ci.yml
> +# SPDX-FileCopyrightText: 2021-2025 Robin Schneider <ypid@riseup.net>
Can you drop the 3431c4669039d9030e95d70594e8cf129baee8cd commit now that we specified this better in https://github.com/opening-hours/opening_hours.js?tab=readme-ov-file#license?

2025-04-06 17:04 UTC, ypid commented on .editorconfig
> +# SPDX-FileCopyrightText: © 2015 Simon Legner <Simon.Legner@gmail.com>
More a generic comment, not so much related to this line: I prefer if you rebasing ontop of master instead of creating merge commits into master in pull requests. Also, prefer [atomic git commits](https://www.aleksandrhovhannisyan.com/blog/atomic-git-commits/). Tools like [lazygit](https://github.com/jesseduffield/lazygit) and [git-absorb](https://github.com/tummychow/git-absorb) are a big help for all of that.

2025-04-06 17:34 UTC, KristjanESPERANTO commented on scripts/yamlToJson.mjs
>  // Call yamlToJson.mjs [input] [output]
I just removed it.

2025-04-06 18:04 UTC, KristjanESPERANTO commented on .editorconfig
> +# SPDX-FileCopyrightText: © 2015 Simon Legner <Simon.Legner@gmail.com>
Okay, I rebased on top on master. Thanks for the tips. So far, I'm not getting on so well with this tools. Your feedback is very welcome, I'm always learning something new.

2025-04-06 18:05 UTC, KristjanESPERANTO commented on .github/workflows/ci.yml
> +# SPDX-FileCopyrightText: 2021-2025 Robin Schneider <ypid@riseup.net>
Done.

2025-04-06 18:05 UTC, KristjanESPERANTO commented on LICENSES/AGPL-3.0-only.txt
> +Copyright (C) 2007 Free Software Foundation, Inc. <https://www.fsf.org/>
Understood and undone :slightly_smiling_face:

2025-04-06 18:53 UTC, ypid commented on .editorconfig
> +# SPDX-FileCopyrightText: © 2015 Simon Legner <Simon.Legner@gmail.com>
All right. Don’t worry. I did a rebase with `--rebase-merges` in #479. I will cherry pick your other commits that you added today also to that branch later.

2025-04-06 18:54 UTC, ypid requested changes

2025-04-06 18:54 UTC, ypid commented on Makefile
> +	./node_modules/package-json-validator/lib/bin/pjv.mjs --warnings --recommendations --filename "$<"
That seems to require an update of package-json-validator. Want to include this in that commit (to make it an atomic upgrade)?

2025-04-06 18:59 UTC, KristjanESPERANTO commented on .editorconfig
> +# SPDX-FileCopyrightText: © 2015 Simon Legner <Simon.Legner@gmail.com>
Thank you for your patience and effort! :smiley:

2025-04-06 18:59 UTC, KristjanESPERANTO commented on .editorconfig
> +# SPDX-FileCopyrightText: © 2015 Simon Legner <Simon.Legner@gmail.com>
I didn't know `--rebase-merges` before ...

2025-04-09 18:37 UTC, ypid commented on .editorconfig
> +# SPDX-FileCopyrightText: © 2015 Simon Legner <Simon.Legner@gmail.com>
You are welcome. I probably should have merged this first to avoid the big rebase. Well. #479 is now ready. It basically has no diff compared to this branch, but it includes merge commits and I have modified the commit that touched LICENSES files instead of using your undo commit. Can you give an approval for that, then I will merge that?

2025-05-21 18:26 UTC, closed without merging